# Generated by Django 4.2.1 on 2023-05-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('place', models.TextField(max_length=20)),
                ('age', models.IntegerField()),
                ('email_field', models.EmailField(max_length=254)),
            ],
        ),
    ]
